#theme: jekyll-theme-cayman
remote_theme: zendesk/jekyll-theme-zendesk-garden
remote_theme: alshedivat/al-folio

title: "David Sundström"
description: "My personal webpage"

sidebar:
  - publications
  - software
  - music

