theme: jekyll-theme-cayman

title: "David Sundström"
description: "My personal webpage"

sidebar:
  - publications
  - software
  - music


# Navigation menu
#links:
#  - title: "Home"
#    url: "/"
#  - title: "Publications"
#    url: "/publications"
#  - title: "Software"
#    url: "/software"
#  - title: "Music"
#    url: "/music"
