theme: jekyll-theme-minimal-mistakes

title: "David Sundström"
description: "My personal webpage"

# Navigation menu
links:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications"
  - title: "Software"
    url: "/software"
  - title: "Music"
    url: "/music"
