theme: jekyll-theme-cayman

title: "David Sundström"
description: "My personal webpage"

sidebar:
  navigation:
    - title: Publications
      id: publications
    - title: Software
      id: software
    - title: Music
      id: music

