#theme: jekyll-theme-cayman
remote_theme: alshedivat/al-folio

plugins:
  - jekyll-remote-theme # Ensure this plugin is included

title: "David Sundström"
description: "My personal webpage"

sidebar:
  - publications
  - software
  - music

