#theme: jekyll-theme-cayman
remote_theme: zendesk/jekyll-theme-zendesk-garden

title: "David Sundström"
description: "My personal webpage"

sidebar:
  navigation:
    - title: Publications
      id: publications
    - title: Software
      id: software
    - title: Music
      id: music

